#+TITLE: Crystal Website 💖
#+AUTHOR: Crystalarch
#+OPTIONS: ^:{}
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/style.css">
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="/favicon.png">
* Small introduction !!!!
** Welcome OwO !!!!
Welcome everyone to my personal website UwU, it's pretty simple and minimalist so forgive me pwease if it breaks your eyes.
** Who the fuck am I ?
My name is Crystal , I'm 16 years old ( my bday is in the 9th of december :D ) and i'm from Algeria, I speak 4 languages (French English Arabic and Tamazight) . Linux and foss enthusiast , one of my dreams is living abroad and joining the FSFondation and work in IT !!!
** Ok but what is this website ?
Good question , this website made entirely in org mode (doom emacs gang) and my simple css config file  is mainly a rant website , a personal diary, some blog posts about things i discover , and my opinions and projects i work in . So expect to not fully agree with my POV ,and it's fine, cuz we love you because of our differences !! :3 Also this website is under the MIT license amazing amirit ?

** Great how can i contact you though ?
If you wanna drive by and say hello, feel free to DM me on discord Crystal on meth#7407 !! Oh also don't forget to check my github profile here : https://github.com/Archenagechan
** License( TL;DR: you are free to reuse any part of my code idgaf im just trying doom emacs thingies )
#+BEGIN_QUOTE
The MIT License (MIT)

Copyright (c) 2022 Crystal

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

#+END_QUOTE
* End of Exams, DWM scripts update and life updates (and more :D) /27|03|2022/
So it has been over a week since i wrote to this website that no one reads anyways . But i finally finished my exams🎉 whouhouuuu only one year for the bacalorea exam .  I mostly did well , fucked up in maths, but hey , better than nothing :D. Also while i was not present, i took my time to revamp my dwm build (which needs a couple of pushes to my repo) and enhanced my theme picker to make it a bit nicer, with a random option and a notification ..Who doesn't love some randomness in their life. As for life , well... Im finally on a date with someone IRL, a cute guy named Luke , it means the world to me to have him with me so i wanted to share my joy with this org document. Anyways thats all , have a nice day , night or launch , see y'all
* Earthquake /19|03|2022/
As the title says, today an earthquake stroke the coast of Bejaia , named Cap Carbon , with a magnitude of 6.0 . And surprisingly no bouncing quakes....weird , what is weirder is that, last year , and exactly this day (well the day before, but still) a similar..no , identical quake stroke in the Same spot with the same magnitude, only difference is that the first was at night, and today was at 11AM.
Im safe, everyone is safe and no cracks in buildings appart from the University Campus appeared.
* First impression with an android 12 rom (phone) /09|03|2022/
First of all ,sorry for being absent, life is kinda keeping me busy. ANYWAYS happy womens day to start with !! Sooo Android 12 , after fixing my Redmi 9A, i went for the first time with a custom rom "Nusantara ROM" which uses the Android 12 version . And my first impression is: WAW. A12 is indeed a step up from Miui Android 10 . Everything goes well with eachother, a lot of privacy settings, hell i didnt even have to debloat my phone cuz it didnt have bloatware. The theming engine really reminds me of pywal on linux, but on steroides .

One small problem i had was the fact the file manager doesnt let you choose the root of your sd card as a location for some apps, other than that, 10/10 would recommend
* I fucking hate Xiaomi and Mediatek /24|02|2022/
So yesterday , the worse thing that could happen to me , happened . While i was trying to install a custom rom on my phone (Redmi 9A) which got recommended to me by an indian guy saying "oh yeah oh yeah it works on Redmi 9A" well guess what .__. it doesn't , now my phone is bootlooping, and i have 0 internet to download the ROM (4gb of size 😭) hell , i don't even know when this website will get commited , but one thing for sure:  Fuck Mediatek , and fuck me for believing random indians on youtube .__.
* Quick Patch Note /18|02|2022/
It appeared that the website fonts didn't load for people without JetBrains Mono font installed and so the website looked broken-ish ! Thank you Marie for letting me know <3 , Now everything should be fixed...i hope , otherwise just install that font ,pretty cool one i might add :D !
* HP , the keyboard, and what the fuck happened /17|02|2022/
I fucking hate this , my keyboard randomly stopped reading input from some keys , which are : aqwedcrfvtgb1345 . Well guess i will have to buy a new keyboard for my HP ELITEBOOK 840 G2 (yeah pretty old laptop) , it might not be that bad, since i lost the trackpoint ,and it will be a great opportunity to replace it.
* Today I learned the sysrq key on my keyboard did a thing!! /16|02|2022/
I was really surprised when i found out that using *ALT+SYSRQ(the print key)+ r k* , will kill all programs EXCEPT the init on the current console.
Or *ALT+SYSRQ+r e i s u o(or b for reboot)* to shutdown your pc, really cool
