#+TITLE: Crystal Website 💖
#+AUTHOR: Crystalarch
#+OPTIONS: ^:{}
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/colors.css">
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/style.css">
#+HTML_HEAD: <link rel="icon" type="image/x-icon" href="/favicon.png">
#+OPTIONS: html-style:nil

* Welcome OwO !!!!
Welcome everyone to my personal website UwU, it's pretty simple and minimalist so forgive me pwease if it breaks your eyes.
* Who the fuck am I ?
My name is Crystal, I'm 16 years old (my bday is in the 9th of december :D) and I'm from Algeria, I speak 4 languages (French English Arabic and Tamazight). Linux and foss enthusiast, one of my dreams is living abroad and work in IT/AI !!!
* Ok, but what is this website ?
Good question, this website made entirely in org mode (doom emacs gang) and my simple CSS config and serves as a "starting point" to people that want to get to know me, or something, idk really haha !! :3 This website is under the WTFPL license amazing amirit ?

* Great how can I contact you though ?
If you want to drive by and say hello, feel free to DM me on discord *Crystal-TD#1220*!! Oh, also don't forget to check my GitHub profile here : https://github.com/crystal-trd
* License(TL;DR: you are free to reuse any part of my code idgaf im just trying doom emacs thingies)
           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
                   Version 2, December 2004

Copyright © 2004 Sam Hocevar <sam@hocevar.net>

Everyone is permitted to copy and distribute verbatim or modified
copies of this license document, and changing it is allowed as long
as the name is changed.

           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

 0. You just DO WHAT THE FUCK YOU WANT TO.

* Links :
Orchid Linux's github page : https://github.com/orchid-linux/orchid/

Orchid Linux's website : https://orchid-linux.org/

Be paranoid (hanna's website, highly recommend if you care about privacy) : https://beparanoid.de

SearxNG : https://docs.searxng.org/

Online Spyware Watchdog : https://spyware.neocities.org/
