/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_tags.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fsignal.c"
#include "movestack.c"
#include "restartsig.c"
#include "scratchpad.c"
#include "sticky.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_bstack.c"
#include "layout_bstackhoriz.c"
#include "layout_centeredmaster.c"
#include "layout_centeredfloatingmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_flextile-deluxe.c"
#include "layout_gapplessgrid.c"
#include "layout_grid.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_nrowgrid.c"
#include "layout_tile.c"

