--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/crystal/Pictures/Wallpapers/brutusbrodie.png"

-- Special
background="#0c0a0a"
foreground="#c8c5bd"
cursor="#c8c5bd"

-- Colors
color0="#0c0a0a"
color1="#504E4C"
color2="#6E675C"
color3="#90664B"
color4="#998B72"
color5="#CBA165"
color6="#4F88AC"
color7="#c8c5bd"
color8="#8c8984"
color9="#504E4C"
color10="#6E675C"
color11="#90664B"
color12="#998B72"
color13="#CBA165"
color14="#4F88AC"
color15="#c8c5bd"
