# Shell variables
# Generated by 'wal'
wallpaper='/home/crystal/Pictures/Wallpapers/brutusbrodie.png'

# Special
background='#0c0a0a'
foreground='#c8c5bd'
cursor='#c8c5bd'

# Colors
color0='#0c0a0a'
color1='#504E4C'
color2='#6E675C'
color3='#90664B'
color4='#998B72'
color5='#CBA165'
color6='#4F88AC'
color7='#c8c5bd'
color8='#8c8984'
color9='#504E4C'
color10='#6E675C'
color11='#90664B'
color12='#998B72'
color13='#CBA165'
color14='#4F88AC'
color15='#c8c5bd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
